import type { Candidate, Job, DashboardStats } from "./types"

export const mockJob: Job = {
  id: "job-001",
  title: "Senior Machine Learning Engineer",
  department: "Engineering",
  location: "Remote / Bangalore",
  status: "active",
  requiredSkills: ["Python", "TensorFlow", "PyTorch", "AWS", "MLflow", "SQL"],
  preferredSkills: ["Docker", "Kubernetes", "Spark", "Scala"],
  experienceYears: 5,
  responsibilities: [
    "Design and deploy production ML pipelines at scale",
    "Collaborate with data scientists to productionize models",
    "Build robust feature engineering and monitoring systems",
    "Mentor junior engineers and conduct technical reviews",
    "Drive architectural decisions for the ML platform",
  ],
  domains: ["Machine Learning", "MLOps", "Deep Learning"],
  education: "Bachelor's or Master's in Computer Science, Statistics, or related field",
  candidateCount: 8,
  shortlistedCount: 3,
  createdAt: "2026-05-01",
  simplifiedJD: `We're looking for a Senior ML Engineer who loves turning research into production systems. You'll be the bridge between our data science and platform teams.

**What you'll do:**
- Build and maintain scalable ML pipelines that serve millions of predictions daily
- Work closely with data scientists to deploy and monitor models in production
- Design feature stores and experiment tracking infrastructure
- Mentor a small team of ML engineers

**Must have:** Strong Python skills, hands-on experience with TensorFlow or PyTorch, cloud deployment (AWS preferred), and 5+ years in production ML roles.

**Nice to have:** Container orchestration, distributed computing with Spark, or experience with LLMs.

**Ideal candidate:** Someone who is equally comfortable reading a research paper and debugging a Kubernetes pod. You ship fast, care about model performance, and obsess over reliability.`,
}

export const mockCandidates: Candidate[] = [
  {
    id: "c1",
    name: "Priya Sharma",
    email: "priya.sharma@email.com",
    phone: "+91 98765 43210",
    currentRole: "ML Engineer @ Flipkart",
    totalYears: 6.5,
    skills: ["Python", "TensorFlow", "PyTorch", "AWS", "MLflow", "SQL", "Docker", "Kubernetes"],
    matchedRequired: ["Python", "TensorFlow", "PyTorch", "AWS", "MLflow", "SQL"],
    matchedPreferred: ["Docker", "Kubernetes"],
    education: "M.Tech, IIT Bombay",
    companies: ["Flipkart", "Razorpay"],
    summary: "6+ years building production ML systems at scale. Led MLOps platform serving 50M daily predictions. Strong in deep learning and distributed systems.",
    scores: {
      skillMatch: 100,
      skillExperience: 92,
      totalExperience: 100,
      bonus: 100,
      skillScore: 97,
      ragScore: 91,
      hrScore: 88,
      finalScore: 92,
    },
    status: "shortlisted",
    qualifierQuestions: [
      "Describe your experience designing feature pipelines for a recommendation system at scale. What were the key tradeoffs?",
      "How have you handled model drift in production? Walk me through your monitoring and retraining strategy.",
      "You mentioned using MLflow — how did you integrate experiment tracking into your CI/CD pipeline?",
      "What's your approach to debugging latency issues in a TensorFlow Serving deployment?",
      "How do you decide when to retrain vs. fine-tune an existing production model?",
    ],
    hrNotes: "Strong technical depth. Excellent system design instincts.",
    filename: "priya_sharma_resume.pdf",
  },
  {
    id: "c2",
    name: "Rahul Verma",
    email: "rahul.verma@email.com",
    currentRole: "Senior Data Scientist @ Swiggy",
    totalYears: 5.0,
    skills: ["Python", "PyTorch", "SQL", "AWS", "Spark", "MLflow"],
    matchedRequired: ["Python", "PyTorch", "SQL", "AWS", "MLflow"],
    matchedPreferred: ["Spark"],
    education: "B.Tech, NIT Trichy",
    companies: ["Swiggy", "Walmart Labs"],
    summary: "5 years in applied ML with strong focus on NLP and recommender systems. Built real-time delivery ETA models. Experienced in A/B testing at scale.",
    scores: {
      skillMatch: 83,
      skillExperience: 80,
      totalExperience: 80,
      bonus: 50,
      skillScore: 80,
      ragScore: 83,
      hrScore: 78,
      finalScore: 81,
    },
    status: "reviewing",
    qualifierQuestions: [
      "Your ETA model — how did you handle distributional shift between cities with different traffic patterns?",
      "Walk me through how you'd deploy a PyTorch model for inference at under 50ms p99 latency.",
      "How have you used Spark for feature generation in your current role? What scale?",
      "Describe a time you reduced model complexity without sacrificing meaningful accuracy.",
      "How do you structure model evaluation beyond offline AUC — what production metrics matter most to you?",
    ],
    filename: "rahul_verma_resume.pdf",
  },
  {
    id: "c3",
    name: "Aisha Khan",
    email: "aisha.khan@email.com",
    currentRole: "ML Platform Engineer @ Meesho",
    totalYears: 4.5,
    skills: ["Python", "TensorFlow", "AWS", "Docker", "Kubernetes", "SQL"],
    matchedRequired: ["Python", "TensorFlow", "AWS", "SQL"],
    matchedPreferred: ["Docker", "Kubernetes"],
    education: "B.E., BITS Pilani",
    companies: ["Meesho", "PhonePe"],
    summary: "Built ML infrastructure including training clusters, model registries, and deployment automation. Focused on MLOps and platform reliability.",
    scores: {
      skillMatch: 67,
      skillExperience: 78,
      totalExperience: 72,
      bonus: 100,
      skillScore: 74,
      ragScore: 79,
      hrScore: 72,
      finalScore: 75,
    },
    status: "reviewing",
    filename: "aisha_khan_resume.pdf",
  },
  {
    id: "c4",
    name: "Dev Patel",
    email: "dev.patel@email.com",
    currentRole: "Data Scientist @ Paytm",
    totalYears: 4.0,
    skills: ["Python", "SQL", "TensorFlow", "Scikit-learn", "MLflow"],
    matchedRequired: ["Python", "SQL", "TensorFlow", "MLflow"],
    matchedPreferred: [],
    education: "M.Sc. Statistics, Delhi University",
    companies: ["Paytm", "HDFC"],
    summary: "4 years in financial ML — fraud detection, credit scoring, and risk modeling. Strong statistical foundations and solid Python skills.",
    scores: {
      skillMatch: 67,
      skillExperience: 65,
      totalExperience: 62,
      bonus: 0,
      skillScore: 64,
      ragScore: 69,
      hrScore: 0,
      finalScore: 70,
    },
    status: "pending",
    filename: "dev_patel_resume.pdf",
  },
  {
    id: "c5",
    name: "Mei Lin",
    email: "mei.lin@email.com",
    currentRole: "Junior ML Engineer @ Infosys",
    totalYears: 2.5,
    skills: ["Python", "Keras", "SQL", "Docker"],
    matchedRequired: ["Python", "SQL"],
    matchedPreferred: ["Docker"],
    education: "B.Tech, VIT Vellore",
    companies: ["Infosys"],
    summary: "2.5 years experience. Worked on image classification and NLP projects. Good Python fundamentals, but limited production exposure.",
    scores: {
      skillMatch: 33,
      skillExperience: 40,
      totalExperience: 38,
      bonus: 25,
      skillScore: 37,
      ragScore: 52,
      hrScore: 0,
      finalScore: 43,
    },
    status: "pending",
    filename: "mei_lin_resume.pdf",
  },
  {
    id: "c6",
    name: "Carlos Ruiz",
    email: "carlos.ruiz@email.com",
    currentRole: "Backend Engineer @ TCS",
    totalYears: 5.0,
    skills: ["Java", "Python", "SQL", "AWS", "Spring Boot"],
    matchedRequired: ["Python", "SQL", "AWS"],
    matchedPreferred: [],
    education: "B.Tech, Anna University",
    companies: ["TCS", "Wipro"],
    summary: "5 years backend engineering. Transitioning to ML — completed Andrew Ng's deep learning specialization. Limited hands-on ML in production.",
    scores: {
      skillMatch: 50,
      skillExperience: 35,
      totalExperience: 60,
      bonus: 0,
      skillScore: 44,
      ragScore: 41,
      hrScore: 0,
      finalScore: 43,
    },
    status: "rejected",
    filename: "carlos_ruiz_resume.pdf",
  },
  {
    id: "c7",
    name: "Sarah Johnson",
    email: "sarah.j@email.com",
    currentRole: "Research Scientist @ Academia",
    totalYears: 3.0,
    skills: ["Python", "PyTorch", "R", "MATLAB"],
    matchedRequired: ["Python", "PyTorch"],
    matchedPreferred: [],
    education: "PhD (ongoing), IISc Bangalore",
    companies: ["IISc (Research)"],
    summary: "Strong research background in computer vision. Published 3 papers. Limited industry/production experience — primarily research-focused.",
    scores: {
      skillMatch: 33,
      skillExperience: 55,
      totalExperience: 42,
      bonus: 0,
      skillScore: 41,
      ragScore: 58,
      hrScore: 0,
      finalScore: 46,
    },
    status: "pending",
    filename: "sarah_johnson_resume.pdf",
  },
  {
    id: "c8",
    name: "Tom Walsh",
    email: "tom.walsh@email.com",
    currentRole: "Data Analyst @ Accenture",
    totalYears: 3.5,
    skills: ["Python", "SQL", "Excel", "Tableau", "Power BI"],
    matchedRequired: ["Python", "SQL"],
    matchedPreferred: [],
    education: "BBA, Symbiosis",
    companies: ["Accenture"],
    summary: "3.5 years as data analyst. Proficient in SQL and Python for data analysis. No ML engineering or model deployment experience.",
    scores: {
      skillMatch: 33,
      skillExperience: 25,
      totalExperience: 46,
      bonus: 0,
      skillScore: 31,
      ragScore: 28,
      hrScore: 0,
      finalScore: 30,
    },
    status: "rejected",
    filename: "tom_walsh_resume.pdf",
  },
]

export const mockStats: DashboardStats = {
  activeJobs: 4,
  totalCandidates: 8,
  shortlisted: 3,
  avgScore: 60,
  processingTime: "2.4 min",
  thisWeek: 8,
}

export const mockJobs: Job[] = [
  mockJob,
  {
    id: "job-002",
    title: "Product Manager — AI Platform",
    department: "Product",
    location: "Bangalore",
    status: "active",
    requiredSkills: ["Product Strategy", "Data Analysis", "SQL", "Stakeholder Management"],
    preferredSkills: ["ML Familiarity", "Agile", "Figma"],
    experienceYears: 4,
    responsibilities: [],
    domains: ["Product Management", "AI/ML"],
    education: "MBA preferred",
    candidateCount: 12,
    shortlistedCount: 4,
    createdAt: "2026-04-28",
  },
  {
    id: "job-003",
    title: "Data Engineer",
    department: "Data",
    location: "Remote",
    status: "draft",
    requiredSkills: ["Python", "Spark", "Kafka", "Airflow", "SQL"],
    preferredSkills: ["dbt", "Flink", "Iceberg"],
    experienceYears: 3,
    responsibilities: [],
    domains: ["Data Engineering", "Streaming"],
    education: "B.Tech in CS or related",
    candidateCount: 0,
    shortlistedCount: 0,
    createdAt: "2026-05-05",
  },
]
